version: '3'

services:
  gerrit:
    image: gerritcodereview/gerrit
    volumes:
       - git-volume:/var/gerrit/git
       - index-volume:/var/gerrit/index
       - cache-volume:/var/gerrit/cache
       - etc-volume:/var/gerrit/etc
    ports:
       - "29418:29418"
       - "8080:8080"
    environment:
      - CANONICAL_WEB_URL=http://vm_ip:8080
volumes:
  git-volume:
  index-volume:
  cache-volume:
  etc-volume:
  
